### ISSUE TITLE
Vignette not in built package

### ISSUE THREAD

**Issue by cfbeuchel** [holgerman/HT12ProcessoR#2]
When installing the package, the vignette folder is not in the package directory in my local library. This is probably due to the vignette not passing `devtools::check()`, which fails when trying to build the vignette. Also, building the package via `devtools::build()` only succeeds when `vignettes = F` 

build_vignettes fails with:

Building HT12ProcessoR vignettes
Quitting from lines 134-136 (HT12v4_Preprocessing_Example_Run.Rmd) 
Fehler: processing vignette 'HT12v4_Preprocessing_Example_Run.Rmd' failed with diagnostics:
kann Verbindung nicht öffnen

**Comment by holgerman** [comment]
May be the building process has problems using the data from Inst/ExtData that is part of the building process?

**Comment by cfbeuchel** [comment]
I found a passage in Hadley Wickham's RPackages book about this:
http://r-pkgs.had.co.nz/data.html -> under Raw Data

It is recommended to use `system.file` to locate files in `inst/extdata`

I'll experiment with this on my newly created branch and create a pull-request once it works

**Comment by cfbeuchel** [comment]
#6 implements this and should resolve this issue
