### ISSUE TITLE
knitting of vignette fails

### ISSUE THREAD

**Issue by cfbeuchel** [holgerman/HT12ProcessoR#3]
When knittin the HT12v4_Preprocessing_Example_Run.Rmd the process fails with the error message: 

Line 307:
Error in plot.new() : figure margins too large Calls: <Anonymous> ... boxplot -> boxplot.default -> do.call -> bxp -> plot.new -> Execution halted

All chunks run without problem when executed from within the .Rmd file. The error occurs only when knitting the whole file.

**Comment by holgerman** [comment]
Thanks! Can we try to adapt parameters knitr::opts_chunk$set( fig.width = 12 , fig.height = 8) or something similar?

**Comment by cfbeuchel** [comment]
OK, I think the problem was the missing setting of `fig.width` and `fig.height` in the vignette. After setting the values you provided, the vignette knitted without problem.
