### ISSUE TITLE
filterTechnicallyFailed() warning

### ISSUE THREAD

**Issue by cfbeuchel** [holgerman/HT12ProcessoR#4]
When running through the vignette, the function above in step 5 returns two warning messages:

`In min(x) : no non-missing arguments to min; returning Inf`
`In max(x) : no non-missing arguments to min; returning -Inf`

is this of any concern? The final message of the function says that no samples were removed due to atypical combination of control probe levels.

**Comment by holgerman** [comment]
Seems to be related to a min(c()) problem. Thanks.

**Comment by holgerman** [comment]
Fixed in 0.0.11. The reason was a descriptive check for a the range of the technical score, done separately for samples with and without atypical combination of control probe levels. In case of no atypical samples, min/max was determined in a zero-sized group.
