### ISSUE TITLE
Archive Roadmap.Rmd

### ISSUE THREAD

**Issue by cfbeuchel** [holgerman/HT12ProcessoR#7]
The old vignette "Roadmap.Rmd" is redundant due to a reworked, fully executable and properly buildable version now being available. The content has not been changed, however. Only formatting and path-finding issues have been resolved (see #6).
 
Therefore, I would suggest we archive `Roadmap.Rmd`

**Comment by holgerman** [comment]
Done in Version: 0.0.7
