### ISSUE TITLE
createExpressionSet()-Warnings/NA & negative expression values

### ISSUE THREAD

**Issue by cfbeuchel** [holgerman/HT12ProcessoR#8]
Hi!

When using the above mentioned function I receive a variety of warning messages. Apparently, when reading all the probe information, the function identifies `NA`s in the probe data but fails to remove the probes. The first warnings are as follows:

`Warnmeldungen:
1: In createExpressionSet(ht12object = prepro_ht12, paramfile = myparamfile) :
  Problem found: 'NA' as expression value not allowed.`

`2: In createExpressionSet(ht12object = prepro_ht12, paramfile = myparamfile) :
  Problem found: negative gene expression values.`

`3: In createExpressionSet(ht12object = prepro_ht12, paramfile = myparamfile) :
  Problem found: negative expression values or NA values still exists but are not allowed.`

The following warnings accumulate in this fashion:
`4: In merge.data.frame(all_con, con, by = "ProbeID", all.x = T,  ... :
  column names ‘TargetID.x’, ‘TargetID.y’ are duplicated in the result`

`5: In merge.data.frame(all_con, con, by = "ProbeID", all.x = T,  ... :
  column names ‘TargetID.x’, ‘TargetID.y’ are duplicated in the result`

`6: In merge.data.frame(all_con, con, by = "ProbeID", all.x = T,  ... :
  column names ‘TargetID.x’, ‘TargetID.y’, ‘TargetID.x’, ‘TargetID.y’ are duplicated in the result`

`7: In merge.data.frame(all_con, con, by = "ProbeID", all.x = T,  ... :
  column names ‘TargetID.x’, ‘TargetID.y’, ‘TargetID.x’, ‘TargetID.y’ are duplicated in the result`

`8: In merge.data.frame(all_con, con, by = "ProbeID", all.x = T,  ... :
  column names ‘TargetID.x’, ‘TargetID.y’, ‘TargetID.x’, ‘TargetID.y’, ‘TargetID.x’, ‘TargetID.y’ are duplicated in the result`

`9: In merge.data.frame(all_con, con, by = "ProbeID", all.x = T,  ... :
  column names ‘TargetID.x’, ‘TargetID.y’, ‘TargetID.x’, ‘TargetID.y’, ‘TargetID.x’, ‘TargetID.y’ are duplicated in the result`

This goes on for the rest of the warnings()-buffer, getting continuously longer, stacking more of the `TargetID.x` and `TargetID.y` mentions:

`50: In merge.data.frame(all_con, con, by = "ProbeID", all.x = T,  ... :
  column names ‘TargetID.x’, ‘TargetID.y’, ‘TargetID.x’, ‘TargetID.y’, ‘TargetID.x’, ‘TargetID.y’, ‘TargetID.x’, ‘TargetID.y’, ‘TargetID.x’, ‘TargetID.y’, ‘TargetID.x’, ‘TargetID.y’, ‘TargetID.x’, ‘TargetID.y’, ‘TargetID.x’, ‘TargetID.y’, ‘TargetID.x’, ‘TargetID.y’, ‘TargetID.x’, ‘TargetID.y’, ‘TargetID.x’, ‘TargetID.y’, ‘TargetID.x’, ‘TargetID.y’, ‘TargetID.x’, ‘TargetID.y’, ‘TargetID.x’, ‘TargetID.y’, ‘TargetID.x’, ‘TargetID.y’, ‘TargetID.x’, ‘TargetID.y’, ‘TargetID.x’, ‘TargetID.y’, ‘TargetID.x’, ‘TargetID.y’, ‘TargetID.x’, ‘TargetID.y’, ‘TargetID.x’, ‘TargetID.y’, ‘TargetID.x’, ‘TargetID.y’, ‘TargetID.x’, ‘TargetID.y’, ‘TargetID.x’, ‘TargetID.y’, ‘TargetID.x’, ‘TargetID.y’ are duplicated in the result`

The ExpressionSet still gets created nonetheless but I don't think the NAs/negative expression values have been removed. Do you have any ideas what might be causing this?

**Comment by holgerman** [comment]
TNX for reporting! Fixed in vs. 0.0.11
